title: Widyah Kurniasari # your name (or website title) here
logo: "https://github.com/WidyahK023/widyahhh.github.io/issues/1#issue-1229258537" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PZSIB Data Warehousing, Visualization, and Analysis for Business Insight in Zenius
  <br>
  Statistics Student Undergraduate at Diponegoro University
  <br>
  Semarang, Central Java, Indonesia 
  <br><br>
  <a href="https://www.instagram.com/widyah.kur/">View Instagram Profile</a> 
  <br>
  <a href="https://www.linkedin.com/in/widyah-kurniasari-b9103b229/">View My LinkedIn Profile</a> 
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
